### ISSUE TITLE
vss2tool tries to create earliest tag from VSS; error: tag already exists

### ISSUE THREAD

**Issue by lee-davidson** [trevorr/vss2git#49] opened 2018-07-16 18:44 UTC
I downloaded, built, and ran vss2git successfully last week. Today I needed to run it again. I cleaned out the Git directory, ran it again, and it complained when it first tried to create the very first tag that the tag already exists.

I just hacked around: got rid of the target git directory completely, got rid of a clone, and rebuilt vss2git in Visual Studio. Now it worked fine. There must have been, somehow, some scraps of data left over someplace, but apparently I got rid of them. Anyway, this is a possible issue.

**Comment by trevorr** [comment] 2018-07-19 19:24
Thanks for reporting it, but it sounds more like an issue with deleting the git repository than with vss2git. Also, it would need detailed reproduction steps to be actionable. I'm closing this for now, but feel free to reopen if you can demonstrate how to reproduce the issue and vss2git appears to be the cause.

**Closed by trevorr** 2018-07-19 19:24 UTC

**Comment by lee-davidson** [comment] 2018-07-19 19:51
That's fine. This may well be Git's fault. If I have time I might
experiment a bit, but you can close the issue certainly.
